_BASE_: "Base-CenterNet2.yaml"
MODEL:
  BACKBONE:
    NAME: "build_p67_res2net_fpn_backbone"
  WEIGHTS: "models/C2_LVISCOCO_DR2101_4x.pth"
  RESNETS:
    DEPTH: 101
    WIDTH_PER_GROUP: 26
    DEFORM_ON_PER_STAGE: [False, False, True, True] # on Res4, Res5
    DEFORM_MODULATED: True
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.12, 57.375]
  CENTERNET:
    USE_DEFORMABLE: True
  ROI_HEADS:
    IN_FEATURES: ["p3", "p4"]
    NUM_CLASSES: 8
  ROI_BOX_HEAD:
    USE_FED_LOSS: False
SOLVER:
  MAX_ITER: 50000
  CHECKPOINT_PERIOD: 600000
  LR_SCHEDULER_NAME: "WarmupCosineLR"
  BASE_LR: 0.02
  IMS_PER_BATCH: 32
DATASETS:
  TRAIN: ("bdd100k_train",)
  TEST: ("bdd100k_val",)
INPUT:
  FORMAT: RGB