project: GTR_test_len
program: train_net.py
method: grid
parameters:
#  test_asso_th:
#    values:
#      - 0.4
#      - 0.3
#      - 0.2
#  test_nms_th:
#    values:
#      - 0.5
#      - 0.6
#      - 0.7
#      - 0.8
#      - 0.9
  test_len:
    values:
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
      - 19
      - 20
      - 21
      - 22
      - 23
      - 24
command:
  - ${env}
  - python
  - ${program}
  - "--config"
  - "configs/GTR_BDD_DR2101_C2.yaml"
  - "--eval-only"
  - ${args}
