_BASE_: "Base-CenterNet2.yaml"
MODEL:
  FREEZE_TYPE: BackboneBottomup
  META_ARCHITECTURE: "GTRRCNN"
  BACKBONE:
    NAME: "build_p67_res2net_fpn_backbone"
  WEIGHTS: models/GTR_TAO_DR2101.pth
  RESNETS:
    DEPTH: 101
    WIDTH_PER_GROUP: 26
    DEFORM_ON_PER_STAGE: [False, False, True, True] # on Res4, Res5
    DEFORM_MODULATED: True
  PIXEL_MEAN: [123.675, 116.280, 103.530]
  PIXEL_STD: [58.395, 57.12, 57.375]
  CENTERNET:
    USE_DEFORMABLE: True
    NMS_TH_TEST: 0.6
  ROI_BOX_HEAD:
    USE_SIGMOID_CE: True
    USE_FED_LOSS: False
    DELAY_CLS: True
  ROI_HEADS:
    IN_FEATURES: ["p3"]
    NAME: GTRROIHeads
    PROPOSAL_APPEND_GT: False
    NUM_CLASSES: 8
  ASSO_ON: True
  ASSO_HEAD:
    ASSO_THRESH: 0.1
    ASSO_THRESH_TEST: 0.5
    ASSO_WEIGHT: 1.0
    NO_POS_EMB: True
SOLVER:
  MAX_ITER: 90000
  USE_CUSTOM_SOLVER: True
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  BASE_LR: 0.001
  OPTIMIZER: ADAMW
  BACKBONE_MULTIPLIER: 0.1
  STEPS: [40000,60000]
  WARMUP_ITERS: 5000
  IMS_PER_BATCH: 4
  CLIP_GRADIENTS:
    ENABLED: True
    CLIP_TYPE: "full_model"
    CLIP_VALUE: 3.0
    NORM_TYPE: 2.0
  CHECKPOINT_PERIOD: 20000
INPUT:
  FORMAT: RGB
  CUSTOM_AUG: EfficientDetResizeCrop
  SCALE_RANGE: (1, 1)
  TRAIN_SIZE: 640
  TEST_SIZE: 640
  VIDEO:
    TRAIN_LEN: 24
    TEST_LEN: 24
    SAMPLE_RANGE: 1.
VIDEO_INPUT: True
DATASETS:
  TRAIN: ("bdd100k_train",)
  TEST: ("bdd100k_val",)
DATALOADER:
  SAMPLER_TRAIN: "TrainingSampler"
  NUM_WORKERS: 4
OUTPUT_DIR: "./output/GTR_BDD/auto"
FIND_UNUSED_PARAM: True
TEST:
  EVAL_PERIOD: 20000
