program: train_net.py
method: bayes
metric:
  name: total_loss
  goal: minimize
parameters:
  lr:
    min: 0.00001
    max: 0.05
  optimizer:
    values: ["ADAMW", "SGD"]
command:
  - ${env}
  - python
  - ${program}
  - "--config"
  - "configs/GTR_BDD_DR2101_C2.yaml"
  - "--num-gpus"
  - "4"
  - ${args}
