project: GTR_sweep
program: train_net.py
method: bayes
metric:
  name: total_loss
  goal: minimize
parameters:
  base_lr:
    distribution: log_uniform_values
    min: 0.000001
    max: 0.01
  optimizer:
    values: ["ADAMW", "SGD"]
early_terminate:
  type: hyperband
    min_iter: 5000
command:
  - ${env}
  - python
  - ${program}
  - "--config"
  - "configs/GTR_BDD_DR2101_C2.yaml"
  - "--num-gpus"
  - "4"
  - ${args}
